# Generated by Django 5.0.3 on 2024-05-05 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canteen_site', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Delivered', 'Delivered')], default='Pending', max_length=20),
        ),
    ]
